language: android
jdk:
    - oraclejdk8
before_install:
    - export TERM=dumb # to get clean gradle output
    - # update Android SDK first
    - echo yes | android update sdk --no-ui --all --filter tools
    - # then update SDK components
    - echo yes | android update sdk --no-ui --all --filter platform-tools,build-tools-26.0.3,android-26,extra-android-m2repository,extra-google-m2repository
    - ./gradlew androidDependencies
script:
    - ./gradlew check
